### ISSUE TITLE
Support Parity.js

### ISSUE THREAD

**Issue by jacogr** [chevdor/generator-ethdapp#1]
I would love to make a PR for this, just a bit under the gun, who knows, things may look up soon enough. Anyway, with 1.4 we also expose the `parity.js` APIs in addition to `web3.js`. Actually all our apps and internal dapps use it. (We only still supply `inject.js`/`web3.j`s for historic purposes and since it is what most people use and we like to support variety) It may be good as a generation option. Changes would be:

app/templates/app.js

``` javascript
// subscription APIs available, use it instead of manual polling
parity.api.subscribe('eth_blockNumber', function (error, blockNumber) {
  if (error) {
    console.error('unable to get blockNumber', error);
    return;
  }

  var elem = document.getElementById("currentBlock");
  if (elem) {
    // all numbers values returned as BigNumber, make it look pretty
    elem.innerHTML = blockNumber.toFormat(0);
  }
});
```

app/templates/index.html

```
<script src="/parity-utils/parity.js"></script>
```

**Comment by chevdor** [comment]
OK, since it sounds very parity specific (and great btw!), I will make it as a sub generator called **parity**.

So the default generator will not change and still use web3.
The parity sub generator will contain your change.

The call will be something like `yo ethdapp:parity`

Thanks for the suggestion. Don´t worry about the PR, keep working on parity and shoot the ideas here :)

**Comment by chevdor** [comment]
Your wish is my command :)

`yo ethdapp:parity`

with an extra details for parity, will you stop it? :)

**Comment by collincusce** [comment]
Has this been updated in npm? I just installed and yeoman can't detect the submodule.

**Comment by collincusce** [comment]
Nevermind, the generator is outdated and doesn't work (for instance ~./parity/dapps isn't a thing anymore).

**Comment by chevdor** [comment]
Hi @collincusce. It sounds like 2 issues in one. I did not check out the generator in a while. It sounds like a good opportunity to do so. Thanks for reporting the issue. I will look into it.

**Comment by chevdor** [comment]
See #2
