### ISSUE TITLE
Fix parity path

### ISSUE THREAD

**Issue by chevdor** [chevdor/generator-ethdapp#2]
Report from i @collincusce:
the generator is outdated and doesn't work (for instance ~./parity/dapps isn't a thing anymore).

**Comment by chevdor** [comment]
Hi @collincusce,
I just tested this version and confirm that it works all fine. If you have an issue with the target folder, you can edit the deploy script once the generator is done.

I tested on OSX and I can confirm that it matches the requirements for the very latest parity, still.

If you have an issue it may mean you are using Linux or Windows. More details could help me make it better for your platform. Could you tell me more?

**Comment by collincusce** [comment]
Sure I'm running Ubuntu 16.04 by the way.

Also, just as a heads up, I edited the Parity tutorial about 45 minutes ago because the directories in Linux weren't listed correctly in the tutorial either.  It used to be:

$HOME/.local/share/**parity**/dapps

But it should be:

$HOME/.local/share/**io.parity.ethereum**/dapps

If I don't reply to this in two days, you can close it if you like.

**Comment by collincusce** [comment]
This was my result:

> ccusce@ubuntu:~/dev/mockups$ yo ethdapp:parity
> Error ethdapp:parity 
> 
> You don’t seem to have a generator with the name “ethdapp:parity” installed.
> But help is on the way:
> 
> You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
> Install them with npm install generator-ethdapp:parity.
> 
> To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 
> 
> If yo cannot find the generator, run yo doctor to troubleshoot your system.

**Comment by 5chdn** [comment]
can reproduce the issue with the missing `:parity` generator.

**Comment by 5chdn** [comment]
Also this needs fixing:

    Deploying your DAPP...
    cp: cannot create directory '/home/user/.parity/dapps/dapps.app': No such file or directory
    Done! Don´t forget to restart Parity

https://github.com/chevdor/generator-ethdapp/blob/master/app/templates/deploy.sh#L2

Moving it manually should work though. 

Edit, the generic dapp, manually moved to the right dapps subfolder is working fine.

**Comment by chevdor** [comment]
I guess I could either ask the user to provide his .parity path but as lazy user myself I don´t like the idea plus most users don´t have a clue.

I will find a better solution.

Thank you both for the details. For now, indeed, you can clone the repo, change the path and run `npm link`to get a fix for your ENV.

**Comment by collincusce** [comment]
I was told that, as of the recent release, the parity path will match the paths in: https://github.com/paritytech/parity/wiki/Tutorial-Part-I 

I'm told it's in stable, though I am running beta.

**Comment by collincusce** [comment]
Modified deploy.sh to read:

```
echo "Deploying your DAPP..."
cp -Rpf . ~/.local/share/io.parity.ethereum/dapps/mockupv1.app
echo "Done! Don´t forget to restart Parity"
```

The dapp runs just fine in Parity now. 

Thanks guys!

**Comment by chevdor** [comment]
I just need to figure out the Windows path and I will push the fix. I would be glad if you could test after that.

**Comment by chevdor** [comment]
@collincusce @5chdn Hi guys, I just pushed 0.3.1 to npm.
Thanks for your feedback. Hopefully this is all good now and Windows users got a deploy script just for them on the way.
I close the issue, please reopen if needed.

**Comment by chevdor** [comment]
@collincusce btw, I see no mention of the generator-ethdapp in the tuto, it may help newcomers to get started quicker, feel free to add a ref.
